/* Complete named-colour reconstruction census at small order, by pruned DFS.
 *
 * Corrects scripts/sigma_census.c, which fixed sigma_0 to the identity.  That
 * is not without loss of generality: once cards are matched by the identity
 * (G - i with H - i), relabelling H alone breaks the matching, so the only
 * symmetry of the system space is simultaneous conjugation of G and H.
 *
 * Search space: (sigma_0, ..., sigma_{n-1}), sigma_i a permutation of
 * {0..n-1} fixing i.  Symmetry used: sigma_0 is taken up to conjugation by
 * Sym({1..n-1}) (its conjugacy class representatives), which is valid since
 * conjugating the whole system by rho fixing 0 keeps index 0 in place.
 *
 * Pruning: the edge-slot partition generated by a prefix of rows is finer
 * than that of any completion, so an exact-label globalizer of a prefix is a
 * globalizer of every completion.  A prefix with a globalizer is therefore
 * cut, and every leaf that survives is checked exactly.  A leaf with at least
 * two classes and no globalizer is a counterexample to reconstruction of
 * edge-coloured complete graphs with named colours at order n.
 *
 * Usage: sigma_dfs N [noprune]   (N=5 must give zero hits and, with noprune,
 * 24^5 = 7,962,624 leaves, matching docs/LAST_GLOBALIZER_STRIKE.md.)
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAXN 7
#define MAXE 21

static int N, E, PRUNE = 1;
static int eidx[MAXN][MAXN], eu[MAXE], ev[MAXE];
static int perms[5040][MAXN], nperms;
static int fix[MAXN][720], nfix[MAXN];
static int eimg[5040][MAXE];

static void rec_perm(int *p, int *used, int k) {
    if (k == N) { memcpy(perms[nperms++], p, sizeof(int) * N); return; }
    for (int v = 0; v < N; v++) if (!used[v]) { used[v] = 1; p[k] = v; rec_perm(p, used, k + 1); used[v] = 0; }
}

/* union-find with rollback (union by index stack) */
static int parent[2 * MAXE];
static int find(int x) { while (parent[x] != x) x = parent[x]; return x; }

typedef struct { int changed[2 * MAXE]; int old[2 * MAXE]; int cnt; } Undo;

static void unite(int a, int b, Undo *u) {
    a = find(a); b = find(b);
    if (a == b) return;
    u->changed[u->cnt] = a; u->old[u->cnt] = parent[a]; u->cnt++;
    parent[a] = b;
}
static void rollback(Undo *u) { for (int i = u->cnt - 1; i >= 0; i--) parent[u->changed[i]] = u->old[i]; u->cnt = 0; }

static int cls[2 * MAXE];

static int compute_classes(void) {
    int label[2 * MAXE], k = 0;
    for (int s = 0; s < 2 * E; s++) label[s] = -1;
    for (int s = 0; s < 2 * E; s++) { int r = find(s); if (label[r] < 0) label[r] = k++; cls[s] = label[r]; }
    return k;
}

static int sigG[MAXN][MAXN], sigH[MAXN][MAXN];
static int mapv[MAXN], usedv[MAXN];

static void sort_small(int *a, int len) {
    for (int i = 1; i < len; i++) { int x = a[i], j = i - 1; while (j >= 0 && a[j] > x) { a[j + 1] = a[j]; j--; } a[j + 1] = x; }
}

static int bt(int v) {
    if (v == N) return 1;
    for (int w = 0; w < N; w++) {
        if (usedv[w]) continue;
        if (memcmp(sigG[v], sigH[w], sizeof(int) * (N - 1))) continue;
        int good = 1;
        for (int u = 0; u < v; u++) if (cls[eidx[v][u]] != cls[E + eidx[w][mapv[u]]]) { good = 0; break; }
        if (!good) continue;
        mapv[v] = w; usedv[w] = 1;
        if (bt(v + 1)) return 1;
        usedv[w] = 0;
    }
    return 0;
}

static int has_globalizer(void) {
    int ok = 1;
    for (int e = 0; e < E; e++) if (cls[e] != cls[E + e]) { ok = 0; break; }
    if (ok) return 1;
    for (int v = 0; v < N; v++) {
        int k = 0;
        for (int w = 0; w < N; w++) if (w != v) { sigG[v][k] = cls[eidx[v][w]]; sigH[v][k] = cls[E + eidx[v][w]]; k++; }
        sort_small(sigG[v], N - 1); sort_small(sigH[v], N - 1);
    }
    memset(usedv, 0, sizeof usedv);
    return bt(0);
}

static long long leaves = 0, pruned = 0, hits = 0, nodes = 0;
static int cur[MAXN];

static void dfs(int row) {
    nodes++;
    if (row == N) {
        leaves++;
        int k = compute_classes();
        if (k >= 2 && !has_globalizer()) {
            hits++;
            printf("ZERO-GLOBALIZER classes=%d rows:", k);
            for (int i = 0; i < N; i++) { printf(" ("); for (int v = 0; v < N; v++) printf("%d%s", perms[cur[i]][v], v + 1 < N ? "," : ""); printf(")"); }
            printf("\n"); fflush(stdout);
        }
        return;
    }
    if (PRUNE && row >= 3) {
        /* every edge is covered once rows 0..2 are present (n >= 4) */
        compute_classes();
        if (has_globalizer()) { pruned++; return; }
    }
    for (int k = 0; k < nfix[row]; k++) {
        int t = fix[row][k];
        if (row == 0) {
            /* conjugacy-class representative under Sym({1..N-1}): perms[t] must be lex-min among conjugates */
            int minimal = 1;
            for (int r = 0; r < nperms && minimal; r++) {
                if (perms[r][0] != 0) continue;
                int rinv[MAXN]; for (int v = 0; v < N; v++) rinv[perms[r][v]] = v;
                for (int v = 0; v < N; v++) {
                    int c = perms[r][perms[t][rinv[v]]];
                    if (c < perms[t][v]) { minimal = 0; break; }
                    if (c > perms[t][v]) break;
                }
            }
            if (!minimal) continue;
        }
        cur[row] = t;
        Undo u; u.cnt = 0;
        for (int e = 0; e < E; e++) {
            if (eu[e] == row || ev[e] == row) continue;
            unite(e, E + eimg[t][e], &u);
        }
        dfs(row + 1);
        rollback(&u);
    }
    if (row == 0) fprintf(stderr, "done: nodes=%lld leaves=%lld pruned=%lld hits=%lld\n", nodes, leaves, pruned, hits);
}

int main(int argc, char **argv) {
    N = argc > 1 ? atoi(argv[1]) : 5;
    if (argc > 2 && !strcmp(argv[2], "noprune")) PRUNE = 0;
    if (N < 4 || N > MAXN) return 1;
    E = 0;
    for (int u = 0; u < N; u++) for (int v = u + 1; v < N; v++) { eidx[u][v] = eidx[v][u] = E; eu[E] = u; ev[E] = v; E++; }
    int p[MAXN], used[MAXN]; memset(used, 0, sizeof used); nperms = 0; rec_perm(p, used, 0);
    for (int i = 0; i < N; i++) { nfix[i] = 0; for (int t = 0; t < nperms; t++) if (perms[t][i] == i) fix[i][nfix[i]++] = t; }
    for (int t = 0; t < nperms; t++) for (int e = 0; e < E; e++) eimg[t][e] = eidx[perms[t][eu[e]]][perms[t][ev[e]]];
    for (int s = 0; s < 2 * E; s++) parent[s] = s;
    dfs(0);
    printf("N=%d prune=%d nodes=%lld leaves=%lld pruned-subtrees=%lld zero-globalizer=%lld\n", N, PRUNE, nodes, leaves, pruned, hits);
    return 0;
}
