#!/usr/bin/env python3
"""Design incidence screen: Steiner triple systems generated by Pasch trades.

The incidence graph of a design (points independent, blocks independent,
point-block adjacency) has one card type per point orbit and one per block
orbit, so designs with large automorphism groups give legal-order graphs with
very few card types, the regime where a counterexample has the fewest
coincidences to satisfy.  Bipartite graphs are not a proven reconstructible
class (McKay 2022 verifies them only through order 17), so any collision
here goes straight to hostile verification.

Seeds: the cyclic STS(13) with base blocks {0,1,4}, {0,2,7} mod 13, and the
projective STS(15) (points = nonzero vectors of F_2^4, blocks = {a, b, a+b}).
A Pasch configuration {abc, ade, bdf, cef} is traded for {abd, ace, bcf, def};
the trade keeps the design a Steiner triple system.  A random walk on Pasch
trades with nauty deduplication of the incidence graph collects distinct
systems (STS(13) has exactly 2; STS(15) has 80, of which 79 contain a Pasch
configuration).  The incidence graphs are then bucketed by exact deck.
"""

from __future__ import annotations

import argparse
import itertools
import random
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[1] / "src"))

from grc import Graph, is_isomorphic, same_deck  # noqa: E402

import pynauty  # noqa: E402


def cyclic_sts13():
    blocks = set()
    for base in ((0, 1, 4), (0, 2, 7)):
        for t in range(13):
            blocks.add(frozenset((x + t) % 13 for x in base))
    return 13, blocks


def projective_sts15():
    pts = list(range(1, 16))
    blocks = set()
    for a, b in itertools.combinations(pts, 2):
        blocks.add(frozenset((a, b, a ^ b)))
    return 15, {frozenset(x - 1 for x in bl) for bl in blocks}


def incidence_graph(v, blocks):
    bl = sorted(tuple(sorted(b)) for b in blocks)
    n = v + len(bl)
    rows = [0] * n
    for j, b in enumerate(bl):
        for p in b:
            rows[p] |= 1 << (v + j)
            rows[v + j] |= 1 << p
    return Graph(tuple(rows))


def certificate(g: Graph) -> bytes:
    adj = {x: [y for y in range(g.n) if g.edge(x, y)] for x in range(g.n)}
    return pynauty.certificate(pynauty.Graph(g.n, adjacency_dict=adj))


def pasch_configs(blocks):
    bl = list(blocks)
    by_pair = {}
    for b in bl:
        for pr in itertools.combinations(sorted(b), 2):
            by_pair[pr] = b
    found = set()
    for b1 in bl:
        a, b, c = sorted(b1)
        for x, y, z in ((a, b, c), (b, a, c), (c, a, b)):
            # x is the common point of b1 and b2 (= {x, d, e}); b3 contains y and d; b4 contains z and e
            for b2 in bl:
                if b2 == b1 or x not in b2:
                    continue
                d, e = sorted(b2 - {x})
                for dd, ee in ((d, e), (e, d)):
                    b3 = by_pair.get(tuple(sorted((y, dd))))
                    b4 = by_pair.get(tuple(sorted((z, ee))))
                    if b3 is None or b4 is None:
                        continue
                    if len(b3 & b4) == 1 and b3 != b1 and b3 != b2 and b4 != b1 and b4 != b2:
                        f = next(iter(b3 & b4))
                        if f not in b1 and f not in b2:
                            found.add(frozenset((b1, b2, b3, b4)))
    return list(found)


def trade(blocks, config):
    b1, b2, b3, b4 = list(config)
    pts = set().union(*config)
    # identify a,b,c,d,e,f: a = b1 & b2, b = b1 & b3, c = b1 & b4, d = b2 & b3, e = b2 & b4, f = b3 & b4
    def common(x, y):
        return next(iter(x & y))
    # need the labelling consistent with {abc, ade, bdf, cef}
    for order in itertools.permutations([b1, b2, b3, b4]):
        B1, B2, B3, B4 = order
        try:
            a = common(B1, B2); b = common(B1, B3); c = common(B1, B4)
            d = common(B2, B3); e = common(B2, B4); f = common(B3, B4)
        except StopIteration:
            continue
        if len({a, b, c, d, e, f}) == 6 and B1 == frozenset((a, b, c)) and B2 == frozenset((a, d, e)) and B3 == frozenset((b, d, f)) and B4 == frozenset((c, e, f)):
            new = {frozenset((a, b, d)), frozenset((a, c, e)), frozenset((b, c, f)), frozenset((d, e, f))}
            return (blocks - set(config)) | new
    raise RuntimeError("not a Pasch configuration")


def is_sts(v, blocks):
    cov = Counter()
    for b in blocks:
        for pr in itertools.combinations(sorted(b), 2):
            cov[pr] += 1
    return all(cov[pr] == 1 for pr in itertools.combinations(range(v), 2))


def deck_signature(g: Graph):
    return tuple(sorted(certificate(g.delete_vertex(x)) for x in range(g.n)))


def explore(v, seed_blocks, steps, rng):
    systems = {}
    frontier = [seed_blocks]
    g = incidence_graph(v, seed_blocks)
    systems[certificate(g)] = seed_blocks
    t0 = time.time()
    for _ in range(steps):
        cur = rng.choice(list(systems.values()))
        cfgs = pasch_configs(cur)
        if not cfgs:
            continue
        new = trade(cur, rng.choice(cfgs))
        assert is_sts(v, new)
        c = certificate(incidence_graph(v, new))
        if c not in systems:
            systems[c] = new
    print(f"STS({v}): distinct systems reached by Pasch trades: {len(systems)} ({time.time()-t0:.0f}s)", flush=True)
    return systems


def screen(v, systems):
    buckets = {}
    hits = 0
    for c, blocks in systems.items():
        g = incidence_graph(v, blocks)
        sig = deck_signature(g)
        if sig in buckets and buckets[sig][0] != c:
            hits += 1
            h = incidence_graph(v, buckets[sig][1])
            ok = same_deck(g, h) and not is_isomorphic(g, h)
            print(("HIT" if ok else "REFUTED-ON-REPLAY"), f"STS({v}) incidence graphs n={g.n}", g.to_graph6(), h.to_graph6(), flush=True)
        buckets.setdefault(sig, (c, blocks))
    print(f"STS({v}): incidence graphs n={v + len(next(iter(systems.values())))}: systems={len(systems)} distinct decks={len(buckets)} collisions={hits}", flush=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--steps13", type=int, default=200)
    ap.add_argument("--steps15", type=int, default=3000)
    ap.add_argument("--seed", type=int, default=1)
    a = ap.parse_args()
    rng = random.Random(a.seed)
    v, bl = cyclic_sts13()
    assert is_sts(v, bl)
    screen(v, explore(v, bl, a.steps13, rng))
    v, bl = projective_sts15()
    assert is_sts(v, bl)
    screen(v, explore(v, bl, a.steps15, rng))


if __name__ == "__main__":
    main()
